name = "Tiltfile"
grammar = "starlark"
path_suffixes = ["Tiltfile", "tiltfile", ".tiltfile", ".tilt"]
line_comments = ["# "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "b\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "b'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "r\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "r'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "rb\"", end = "\"", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "rb'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "\"\"\"", end = "\"\"\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'''", end = "'''", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
    ] },
]


[language_servers.tilt]
name = "Tilt LSP"
language = "Tiltfile"
languages = ["Tiltfile"]
